version: "3.8"

services: 
    app:
        container_name: app
        ports:
            - 9090:9090
        build: .
        env_file:
            - .env
        volumes:
            - .:/src/nitd-results/