name: go-docker-heroku-cd

on:
  push:
    branches: ["main"]
  pull_request:
    brances: ["main"]
  
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'nitdresults' }}

jobs:
  deploy:
    name: Deply to Heroku
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker build
        run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

      - name: Publish
        run: |
          heroku container:push web -a  $APP_NAME
          heroku container:release web -a $APP_NAME

